export const USERREQ_LIST_REQUEST = "USERREQ_LIST_REQUEST";
export const USERREQ_LIST_SUCCESS = "USERREQ_LIST_SUCCESS";
export const USERREQ_LIST_FAIL = "USERREQ_LIST_FAIL";
export const USERREQ_LIST_RESET = "USERREQ_LIST_RESET";

export const USERREQ_CREATE_RESET="USERREQ_CREATE_RESET";
export const USERREQ_CREATE_REQUEST = "USERREQ_CREATE_REQUEST";
export const USERREQ_CREATE_SUCCESS = "USERREQ_CREATE_SUCCESS";
export const USERREQ_CREATE_FAIL = "USERREQ_CREATE_FAIL";

export const USERREQ_DELETE_RESET="USERREQ_DELETE_RESET";
export const USERREQ_DELETE_REQUEST = "USERREQ_DELETE_REQUEST";
export const USERREQ_DELETE_SUCCESS = "USERREQ_DELETE_SUCCESS";
export const USERREQ_DELETE_FAIL = "USERREQ_DELETE_FAIL";

export const USERREQ_DETAILS_REQUEST = "USERREQ_DETAILS_REQUEST";
export const USERREQ_DETAILS_SUCCESS = "USERREQ_DETAILS_SUCCESS";
export const USERREQ_DETAILS_FAIL = "USERREQ_DETAILS_FAIL";
export const USERREQ_DETAILS_RESET = "USERREQ_DETAILS_RESET";
