export const WORKREQUEST_LIST_REQUEST = "WORKREQUEST_LIST_REQUEST";
export const WORKREQUEST_LIST_SUCCESS = "WORKREQUEST_LIST_SUCCESS";
export const WORKREQUEST_LIST_FAIL = "WORKREQUEST_LIST_FAIL";
export const WORKREQUEST_LIST_RESET = "WORKREQUEST_LIST_RESET";


export const WORKREQUEST_EDIT_REQUEST = "WORKREQUEST_EDIT_REQUEST";
export const WORKREQUEST_EDIT_SUCCESS = "WORKREQUEST_EDIT_SUCCESS";
export const WORKREQUEST_EDIT_FAIL = "WORKREQUEST_EDIT_FAIL";

export const WORKREQUEST_DELETE_REQUEST = "WORKREQUEST_DELETE_REQUEST";
export const WORKREQUEST_DELETE_SUCCESS = "WORKREQUEST_DELETE_SUCCESS";
export const WORKREQUEST_DELETE_FAIL = "WORKREQUEST_DELETE_FAIL";

export const WORKREQUEST_CREATE_REQUEST = "WORKREQUEST_CREATE_REQUEST";
export const WORKREQUEST_CREATE_SUCCESS = "WORKREQUEST_CREATE_SUCCESS";
export const WORKREQUEST_CREATE_FAIL = "WORKREQUEST_CREATE_FAIL";
export const WORKREQUEST_CREATE_RESET = "WORKREQUEST_CREATE_RESET";

export const WORKREQUEST_UPDATE_REQUEST = "WORKREQUEST_UPDATE_REQUEST";
export const WORKREQUEST_UPDATE_SUCCESS = "WORKREQUEST_UPDATE_SUCCESS";
export const WORKREQUEST_UPDATE_FAIL = "WORKREQUEST_UPDATE_FAIL";
export const WORKREQUEST_UPDATE_RESET = "WORKREQUEST_UPDATE_RESET";
