
export const WORK_LIST_REQUEST = "WORK_LIST_REQUEST";
export const WORK_LIST_SUCCESS = "WORK_LIST_SUCCESS";
export const WORK_LIST_FAIL = "WORK_LIST_FAIL";
export const WORK_LIST_RESET = "WORK_LIST_RESET";


export const WORK_EDIT_REQUEST = "WORK_EDIT_REQUEST";
export const WORK_EDIT_SUCCESS = "WORK_EDIT_SUCCESS";
export const WORK_EDIT_FAIL = "WORK_EDIT_FAIL";

export const WORK_DELETE_REQUEST = "WORK_DELETE_REQUEST";
export const WORK_DELETE_SUCCESS = "WORK_DELETE_SUCCESS";
export const WORK_DELETE_FAIL = "WORK_DELETE_FAIL";

export const WORK_CREATE_REQUEST = "WORK_CREATE_REQUEST";
export const WORK_CREATE_SUCCESS = "WORK_CREATE_SUCCESS";
export const WORK_CREATE_FAIL = "WORK_CREATE_FAIL";
export const WORK_CREATE_RESET = "WORK_CREATE_RESET";

export const WORK_UPDATE_REQUEST = "WORK_UPDATE_REQUEST";
export const WORK_UPDATE_SUCCESS = "WORK_UPDATE_SUCCESS";
export const WORK_UPDATE_FAIL = "WORK_UPDATE_FAIL";
export const WORK_UPDATE_RESET = "WORK_UPDATE_RESET";
