export const REQUEST_LIST_REQUEST = "REQUEST_LIST_REQUEST";
export const REQUEST_LIST_SUCCESS = "REQUEST_LIST_SUCCESS";
export const REQUEST_LIST_FAIL = "REQUEST_LIST_FAIL";
export const REQUEST_LIST_RESET = "REQUEST_LIST_RESET";


export const USERREQ_LIST_REQUEST = "USERREQ_LIST_REQUEST";
export const USERREQ_LIST_SUCCESS = "USERREQ_LIST_SUCCESS";
export const USERREQ_LIST_FAIL = "USERREQ_LIST_FAIL";
export const USERREQ_LIST_RESET = "USERREQ_LIST_RESET";

export const USERREQ_DETAILS_RESET="USERREQ_DETAILS_RESET";
export const USERREQ_DETAILS_REQUEST = "USERREQ_DETAILS_REQUEST";
export const USERREQ_DETAILS_SUCCESS = "USERREQ_DETAILS_SUCCESS";
export const USERREQ_DETAILS_FAIL = "USERREQ_DETAILS_FAIL";

export const USERREQ_EDIT_RESET="USERREQ_EDIT_RESET";
export const USERREQ_EDIT_REQUEST = "USERREQ_EDIT_REQUEST";
export const USERREQ_EDIT_SUCCESS = "USERREQ_EDIT_SUCCESS";
export const USERREQ_EDIT_FAIL = "USERREQ_EDIT_FAIL";

export const REQ_CREATE_SUCCESS = "REQ_CREATE_SUCCESS";
export const REQ_CREATE_REQUEST = "REQ_CREATE_REQUEST";
export const REQ_CREATE_RESET = "REQ_CREATE_RESET";

export const REPORT_LIST_REQUEST = "REPORT_LIST_REQUEST";
export const REPORT_LIST_SUCCESS = "REPORT_LIST_SUCCESS";
export const REPORT_LIST_FAIL = "REPORT_LIST_FAIL";
export const REPORT_LIST_RESET="REPORT_LIST_RESET"