
export const WORKUSER_LIST_REQUEST = "WORKUSER_LIST_REQUEST";
export const WORKUSER_LIST_SUCCESS = "WORKUSER_LIST_SUCCESS";
export const WORKUSER_LIST_FAIL = "WORKUSER_LIST_FAIL";
export const WORKUSER_LIST_RESET = "WORKUSER_LIST_RESET";


export const WORKUSER_EDIT_REQUEST = "WORKUSER_EDIT_REQUEST";
export const WORKUSER_EDIT_SUCCESS = "WORKUSER_EDIT_SUCCESS";
export const WORKUSER_EDIT_FAIL = "WORKUSER_EDIT_FAIL";

export const WORKUSER_DELETE_REQUEST = "WORKUSER_DELETE_REQUEST";
export const WORKUSER_DELETE_SUCCESS = "WORKUSER_DELETE_SUCCESS";
export const WORKUSER_DELETE_FAIL = "WORKUSER_DELETE_FAIL";

export const WORKUSER_CREATE_REQUEST = "WORKUSER_CREATE_REQUEST";
export const WORKUSER_CREATE_SUCCESS = "WORKUSER_CREATE_SUCCESS";
export const WORKUSER_CREATE_FAIL = "WORKUSER_CREATE_FAIL";
export const WORKUSER_CREATE_RESET = "WORKUSER_CREATE_RESET";

export const WORKUSER_UPDATE_REQUEST = "WORKUSER_UPDATE_REQUEST";
export const WORKUSER_UPDATE_SUCCESS = "WORKUSER_UPDATE_SUCCESS";
export const WORKUSER_UPDATE_FAIL = "WORKUSER_UPDATE_FAIL";
export const WORKUSER_UPDATE_RESET = "_WORKUSER_UPDATE_RESET";
